# Generated by Django 4.0.6 on 2022-07-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('membre', models.IntegerField(default=0)),
                ('personnel', models.IntegerField(default=0)),
                ('sauna', models.BooleanField(default=False)),
                ('hamma', models.BooleanField(default=False)),
                ('piscine', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('bar', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=400)),
                ('petiteDescription', models.CharField(max_length=150)),
            ],
        ),
    ]
