# Generated by Django 4.0.6 on 2022-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='personnel',
        ),
    ]
