# Generated by Django 4.0.6 on 2022-07-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0002_personnel_rename_nom_entreprise_nom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entreprise',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
