# Generated by Django 4.0.6 on 2022-07-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
