# Generated by Django 4.0.6 on 2022-07-06 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recherche', '0005_userprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image_publie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image_publie')),
                ('description', models.CharField(max_length=200)),
                ('small_description', models.CharField(max_length=90)),
                ('dpo', models.CharField(max_length=50)),
                ('technical_contact', models.CharField(max_length=50)),
                ('commercial_contact', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
