# Generated by Django 4.0.6 on 2022-07-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0006_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='member',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='staff',
            field=models.IntegerField(default=0),
        ),
    ]
