# Generated by Django 4.0.6 on 2022-07-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0007_entreprise_member_entreprise_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Administrateur'},
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
